// user module
export const UPDATE_AUTH_TOKEN = 'UPDATE_AUTH_TOKEN'
export const CLEAR_AUTH_TOKEN = 'CLEAR_AUTH_TOKEN'
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'
export const UPDATE_CITY = 'UPDATE_CITY'
